markdown_extensions: 
  - fontawesome_markdown
  - admonition
  - codehilite

site_name: 'rvanlande'
site_description: 'My personal website'
site_author: 'Renaud Vanlande'

theme: 'material'

extra:
  palette:
    primary: 'lime'
    accent: 'lime'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
#    text: 'Roboto'
#    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/rvanlande'
    - type: 'twitter'
      link: 'https://twitter.com/RVanlande'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/renaud-vanlande-836616107/'