site_name: La grotte d'Alibaba
markdown_extensions: [fenced_code]

theme: 'material'
extra:
  palette:
    primary: 'lime'
    accent: 'lime'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  social:
    - type: 'github'
      link: 'https://github.com/rvanlande'
    - type: 'twitter'
      link: 'https://twitter.com/RVanlande'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/renaud-vanlande-836616107/'